language: java

jdk:
- openjdk8

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -P !build-extras -B
  - mvn clean jacoco:report coveralls:report -Dcoveralls.token=$COVERALLS_TOKEN -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID cobertura:cobertura

cache:
  directories:
  - "~/.m2/repository"

after_success:
- "./cd/before-deploy.sh"
- "./cd/deploy.sh"